version: "3.8"
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: prueba
    ports:
      - 33061:3306
  mueblesstgo:
    container_name: app-web-simple
    image: danaxar/mueblesstgo
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/prueba
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db